export const auditActionLabel: Record<string, string> = {
  ANALYSIS_CREATED: "Análise criada",
  LABORATORY_CREATED: "Laboratório cadastrado",
  PROPERTY_CREATED: "Propriedade cadastrada",
  PROPERTY_UPDATED: "Propriedade editada",
  PROPERTY_DELETED: "Propriedade excluída",
  FIELD_CREATED: "Talhão cadastrado",
  FIELD_UPDATED: "Talhão editado",
  FIELD_DELETED: "Talhão excluído",
  CROP_SEASON_CREATED: "Safra cadastrada",
  CROP_SEASON_UPDATED: "Safra editada",
  CROP_SEASON_DELETED: "Safra excluída",
  CLIENT_CREATED: "Cliente cadastrado",
  CLIENT_UPDATED: "Cliente editado",
  CLIENT_DELETED: "Cliente excluído",
  TEAM_MEMBER_INVITED: "Membro convidado",
  TEAM_MEMBER_ROLE_CHANGED: "Perfil de membro alterado",
  TEAM_MEMBER_DEACTIVATED: "Membro desativado",
  TEAM_MEMBER_REACTIVATED: "Membro reativado",
  COLLECTION_ORDER_CREATED: "Ordem de coleta criada",
  COLLECTION_POINTS_IMPORTED: "Pontos de coleta importados",
  SAMPLE_POINT_COLLECTED: "Ponto coletado via GPS",
  LAB_IMPORT_COMMITTED: "Laudo laboratorial importado",
};

export const auditEntityLabel: Record<string, string> = {
  analysis: "Análise",
  laboratory: "Laboratório",
  property: "Propriedade",
  field: "Talhão",
  crop_season: "Safra",
  client: "Cliente",
  collection_order: "Ordem de coleta",
  sample_point: "Ponto de coleta",
  user: "Usuário",
};
