"use client";

import { useEffect,useState } from "react";
import { Icon } from "@/components/icon";
import { StatusBadge } from "@/components/ui";

type Prescription={summary:string;diagnosis:Array<{parameterCode:string;value:number;unit:string;interpretation:string;rationale:string}>;recommendations:Array<{inputType:string;quantity:number;unit:string;rationale:string}>;managementPractices:string[];missingInformation:string[];sources:Array<{title:string;institution:string|null;url:string|null}>};
type Generation={id:string;provider:string;model:string;status:"PENDING_REVIEW"|"APPROVED"|"CHANGES_REQUESTED"|"REJECTED";reviewerNote:string|null;reviewedByName:string|null;createdAt:string;responsePayload:{prescription:Prescription;isRealLanguageModel:boolean}};
type HistoryEntry={id:string;status:string;createdAt:string;reviewedByName:string|null};
type Usage={monthlyLimit:number;usedThisMonth:number};
type PkDoseReadiness={ready:boolean;blockers:string[];normalized:{yieldGoalTonPerHa:number|null;cultivationYear:"PRIMEIRO"|"SEGUNDO"|null}};
type UniformPkNutrientReadiness={nutrient:"P2O5"|"K2O";ready:boolean;soilLevel:string|null;matchingCount:number;totalCount:number;basis:"SINGLE_SAMPLE"|"STRICT_PREDOMINANCE"|null;blockers:string[]};
type UniformPkReadiness={ready:boolean;cropCode:string|null;ruleId:string|null;ruleReady:boolean;blockers:string[];nutrients:Record<"P2O5"|"K2O",UniformPkNutrientReadiness>};
type DeterministicPkDoseDecision={ready:boolean;blockers:string[];expected:null|{ruleId:string;nutrient:"P2O5"|"K2O";soilLevel:string;doseKgPerHa:number;minimumKgPerHa:number;maximumKgPerHa:number;isDiscretionaryRange:boolean;source:string}};
type PrescriptionPkValidation={allowed:boolean;failures:Array<{inputType:string;nutrient:"P2O5"|"K2O"|null;blockers:string[];expected:DeterministicPkDoseDecision["expected"]}>};
type Readiness={allowed:boolean;reason:string|null;interpretationStatus:string|null;interpretationId:string|null;prescriptionFreshness?:{current:boolean;reason:string|null}|null;prescriptionPkValidation?:PrescriptionPkValidation|null;recommendationContext?:{cropSeasonId:string;yieldGoal:number|null;yieldGoalUnit:string|null;technologyLevel:string|null;cultivationOrderAfterSoilAnalysis:number|null;cropProfileCode:string|null;updatedAt:string;pkDoseReadiness:PkDoseReadiness;uniformPkReadiness:UniformPkReadiness;deterministicPkDoses:Record<"P2O5"|"K2O",DeterministicPkDoseDecision>}};

const STATUS_META:Record<string,{label:string;tone:"success"|"review"|"waiting"|"danger"}>={PENDING_REVIEW:{label:"Pronta para validar",tone:"review"},APPROVED:{label:"Decisão aprovada",tone:"success"},CHANGES_REQUESTED:{label:"Ajuste solicitado",tone:"review"},REJECTED:{label:"Rejeitada",tone:"danger"}};
const PK_BLOCKER_LABELS:Record<string,string>={YIELD_GOAL_MISSING:"Informe a meta de produtividade.",YIELD_GOAL_INVALID:"A meta precisa ser maior que zero.",YIELD_UNIT_MISSING:"Informe a unidade da meta.",YIELD_UNIT_UNSUPPORTED:"A unidade ainda não possui conversão homologada.",POST_ANALYSIS_CULTIVATION_ORDER_MISSING:"Informe se esta é a 1ª ou 2ª cultura após a análise de solo.",POST_ANALYSIS_CULTIVATION_ORDER_UNSUPPORTED:"A regra atual está homologada somente para 1º e 2º cultivo."};
const UNIFORM_PK_BLOCKER_LABELS:Record<string,string>={PK_CROP_CODE_MISSING:"A cultura da safra não está definida.",PK_CROP_RULE_NOT_IMPLEMENTED:"A cultura ainda não possui tabela P/K liberada.",PK_DETERMINISTIC_TABLE_NOT_IMPLEMENTED:"Não existe tabela P/K implementada para esta cultura.",PK_ELEMENTAL_INPUT_AMBIGUOUS:"P ou K foi informado de forma ambígua; use P2O5 ou K2O.",PK_DUPLICATE_TARGET:"O mesmo alvo P/K foi repetido.",PK_QUANTITY_OR_UNIT_INVALID:"Quantidade ou unidade P/K inválida.",PK_QUANTITY_INVALID:"Quantidade P/K inválida.",PK_UNIT_MUST_BE_KG_PER_HA:"P/K oficial precisa estar em kg/ha.",PK_QUANTITY_DOES_NOT_MATCH_DETERMINISTIC_ENGINE:"A quantidade não coincide com o motor determinístico.",P_NO_CLASSIFIED_OBSERVATION:"Não há classificação válida de fósforo para dose uniforme.",K_NO_CLASSIFIED_OBSERVATION:"Não há classificação válida de potássio para dose uniforme.",P_NO_STRICT_PREDOMINANCE:"Fósforo sem predominância estrita entre os pontos.",K_NO_STRICT_PREDOMINANCE:"Potássio sem predominância estrita entre os pontos.",P_SAMPLE_CLASSIFICATION_AMBIGUOUS:"Há ponto com classificação ambígua de fósforo.",K_SAMPLE_CLASSIFICATION_AMBIGUOUS:"Há ponto com classificação ambígua de potássio.",P_CLASSIFICATION_UNSUPPORTED_FOR_DOSE:"A classe de fósforo não é suportada pela regra ativa.",K_CLASSIFICATION_UNSUPPORTED_FOR_DOSE:"A classe de potássio não é suportada pela regra ativa."};
function blockerLabel(code:string){if(code.startsWith("PK_CONTEXT:"))return PK_BLOCKER_LABELS[code.slice("PK_CONTEXT:".length)]??code;if(code.startsWith("PK_RULE_NOT_READY:"))return `A regra ${code.slice("PK_RULE_NOT_READY:".length)} ainda não está liberada.`;return UNIFORM_PK_BLOCKER_LABELS[code]??code;}
function doseLabel(decision:DeterministicPkDoseDecision|undefined){const e=decision?.expected;if(!e)return"bloqueada";return e.isDiscretionaryRange?`${e.minimumKgPerHa.toLocaleString("pt-BR",{maximumFractionDigits:1})}–${e.maximumKgPerHa.toLocaleString("pt-BR",{maximumFractionDigits:1})} kg/ha`:`${e.doseKgPerHa.toLocaleString("pt-BR",{maximumFractionDigits:1})} kg/ha`;}

export function AgronomicPrescriptionPanel({analysisId,hasLabResults,canRun,canReview}:{analysisId:string;hasLabResults:boolean;canRun:boolean;canReview:boolean}){
  const[latest,setLatest]=useState<Generation|null|undefined>(undefined);const[history,setHistory]=useState<HistoryEntry[]>([]);const[usage,setUsage]=useState<Usage|null>(null);const[readiness,setReadiness]=useState<Readiness|null>(null);const[busy,setBusy]=useState(false);const[contextBusy,setContextBusy]=useState(false);const[contextYieldGoal,setContextYieldGoal]=useState("");const[contextCultivationOrder,setContextCultivationOrder]=useState("");const[note,setNote]=useState("");const[message,setMessage]=useState<{tone:"success"|"danger";text:string}|null>(null);
  async function load(){const response=await fetch(`/api/analyses/${analysisId}/agronomic-prescription`);const data=await response.json().catch(()=>({}));setLatest(data.latest??null);setHistory(data.history??[]);setUsage(data.usage??null);setReadiness(data.readiness??null);}
  useEffect(()=>{void load();},[analysisId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const c=readiness?.recommendationContext;if(!c)return;setContextYieldGoal(c.yieldGoal==null?"":String(c.yieldGoal));setContextCultivationOrder(c.cultivationOrderAfterSoilAnalysis==null?"":String(c.cultivationOrderAfterSoilAnalysis));},[readiness]);
  async function saveRecommendationContext(){const c=readiness?.recommendationContext;if(!c)return;const yieldGoal=Number(contextYieldGoal);const cultivationOrderAfterSoilAnalysis=Number(contextCultivationOrder);if(!Number.isFinite(yieldGoal)||yieldGoal<=0){setMessage({tone:"danger",text:"Informe uma meta de produtividade válida."});return;}if(![1,2].includes(cultivationOrderAfterSoilAnalysis)){setMessage({tone:"danger",text:"Escolha 1º ou 2º cultivo após a análise de solo."});return;}setContextBusy(true);setMessage(null);try{const response=await fetch(`/api/crop-seasons/${c.cropSeasonId}/recommendation-context`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({yieldGoal,yieldGoalUnit:"t/ha",cultivationOrderAfterSoilAnalysis})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error??"Falha ao salvar as informações.");setMessage({tone:"success",text:"Informações salvas. A RAIZ recalculou a prontidão automaticamente."});await load();}catch(error){setMessage({tone:"danger",text:error instanceof Error?error.message:"Falha ao salvar."});}finally{setContextBusy(false);}}
  async function generate(){setBusy(true);setMessage(null);try{const response=await fetch(`/api/analyses/${analysisId}/agronomic-prescription`,{method:"POST"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error??"Falha ao montar a recomendação.");setMessage({tone:"success",text:"Recomendação montada. Agora revise o pacote completo e decida."});await load();}catch(error){setMessage({tone:"danger",text:error instanceof Error?error.message:"Falha ao montar a recomendação."});}finally{setBusy(false);}}
  async function review(decision:"APPROVED"|"CHANGES_REQUESTED"|"REJECTED"){if(!latest)return;setBusy(true);setMessage(null);try{const response=await fetch(`/api/agronomic-prescriptions/${latest.id}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,note})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error??"Falha ao registrar sua decisão.");setNote("");const promoted=data.generation?.promotedRecommendations??0;setMessage({tone:"success",text:decision==="APPROVED"?`Decisão aprovada e assinada${promoted>0?` · ${promoted} recomendação(ões) oficial(is) registrada(s)`:""}.`:decision==="CHANGES_REQUESTED"?"Ajuste solicitado. A versão atual ficou registrada no histórico.":"Decisão rejeitada e preservada no histórico."});await load();}catch(error){setMessage({tone:"danger",text:error instanceof Error?error.message:"Falha ao registrar sua decisão."});}finally{setBusy(false);}}
  if(!hasLabResults)return null;if(latest===undefined)return <div className="agro-loading"><Icon name="clock" size={13}/>A RAIZ está carregando a decisão…</div>;
  const monthlyLimitReached=Boolean(usage&&usage.usedThisMonth>=usage.monthlyLimit);const readyToGenerate=readiness?.allowed===true;const context=readiness?.recommendationContext;const pkReadiness=context?.pkDoseReadiness;const uniformPkReadiness=context?.uniformPkReadiness;const prescriptionStale=Boolean(latest&&readiness?.prescriptionFreshness?.current===false);const pkPromotionBlocked=Boolean(latest?.status==="PENDING_REVIEW"&&readiness?.prescriptionPkValidation?.allowed===false);const statusMeta=prescriptionStale?{label:"Precisa atualizar",tone:"review" as const}:latest?(STATUS_META[latest.status]??{label:latest.status,tone:"waiting" as const}):null;

  return <section id="decisao-raiz" className="ux2-decision-panel">
    <div className="narrative-panel-head"><div><span className="eyebrow">DECISÃO RAIZ</span><h3>O que fazer neste talhão</h3></div>{latest&&statusMeta&&<StatusBadge tone={statusMeta.tone}>{statusMeta.label}</StatusBadge>}</div>
    <p className="ux2-decision-intro">A RAIZ interpreta o laudo, executa as regras homologadas e monta a recomendação. O responsável técnico entra aqui para julgar o trabalho pronto — não para refazer as contas.</p>
    {message&&<div className={`agro-message ${message.tone}`}><Icon name={message.tone==="success"?"check":"warning"} size={14}/><span>{message.text}</span></div>}
    {prescriptionStale&&<div className="agro-message danger"><Icon name="warning" size={14}/><span>{readiness?.prescriptionFreshness?.reason??"Os dados mudaram depois desta recomendação."} Gere uma versão atualizada antes de validar.</span></div>}
    {!latest?<div className="pending-engine" style={{margin:0}}><Icon name={readyToGenerate?"sparkles":"shield"} size={23}/><div><h3>{readyToGenerate?"A leitura técnica está pronta":"Ainda não dá para recomendar com segurança"}</h3><p>{readyToGenerate?"Clique abaixo e a RAIZ monta diagnóstico, cálculos, recomendação, fontes e limitações para sua validação final.":readiness?.reason??"A RAIZ ainda precisa de dados ou cobertura técnica antes de gerar uma recomendação."}</p>{canRun&&<button className="button primary" disabled={busy||monthlyLimitReached||!readyToGenerate} onClick={()=>void generate()}>{busy?"Montando…":monthlyLimitReached?"Limite mensal atingido":readyToGenerate?"Montar recomendação RAIZ":"Veja o que falta abaixo"}</button>}</div></div>:<>
      <p className="ux2-decision-summary">{latest.responsePayload.prescription.summary}</p>
      {latest.responsePayload.prescription.recommendations.length>0?<div className="ux2-recommendation-grid">{latest.responsePayload.prescription.recommendations.map((item,i)=><article className="ux2-recommendation-item" key={`${item.inputType}-${i}`}><span>{item.inputType}</span><strong>{item.quantity.toLocaleString("pt-BR",{maximumFractionDigits:2})} {item.unit}</strong><small>{item.rationale}</small></article>)}</div>:<div className="agro-message waiting"><Icon name="warning" size={14}/><span>A base técnica atual não sustenta uma dose numérica. A RAIZ manteve a lacuna explícita em vez de inventar um número.</span></div>}
      {latest.responsePayload.prescription.missingInformation.length>0&&<div className="narrative-block attention"><h4><Icon name="warning" size={12}/> O que ainda falta</h4><ul>{latest.responsePayload.prescription.missingInformation.map((item,i)=><li key={i}>{item}</li>)}</ul></div>}
      {pkPromotionBlocked&&<div className="agro-message danger"><Icon name="warning" size={14}/><span>Esta versão contém P/K que não coincide com o motor determinístico. Você pode pedir ajuste ou rejeitar, mas a aprovação está bloqueada.</span></div>}
      {canReview&&latest.status==="PENDING_REVIEW"&&!prescriptionStale&&<div className="ux2-review-box"><strong>Sua decisão</strong><p>Leia a recomendação acima. Se quiser conferir a conta, as fontes e os dados usados, abra “Ver como a RAIZ chegou nesses números”.</p><textarea value={note} onChange={(event)=>setNote(event.target.value)} placeholder="Observação técnica (opcional)" rows={2}/><div className="narrative-review-actions"><button className="button primary" disabled={busy||pkPromotionBlocked} onClick={()=>void review("APPROVED")}>{pkPromotionBlocked?"Aprovação bloqueada":"Aprovar decisão"}</button><button className="button secondary" disabled={busy} onClick={()=>void review("CHANGES_REQUESTED")}>Pedir ajuste</button><button className="button ghost" disabled={busy} onClick={()=>void review("REJECTED")}>Rejeitar</button></div></div>}
      {latest.status==="APPROVED"&&<div className="agro-message success"><Icon name="check" size={14}/><span>Decisão aprovada. A interpretação e a recomendação ficaram assinadas e rastreáveis no mesmo fluxo.</span></div>}
      {(prescriptionStale||latest.status==="CHANGES_REQUESTED")&&canRun&&<button className="button secondary" disabled={busy||monthlyLimitReached||!readyToGenerate} onClick={()=>void generate()}>{busy?"Montando…":"Gerar nova versão"}</button>}
    </>}

    <details className="ux2-proof" open={!latest&&Boolean(context&&!pkReadiness?.ready)}><summary>Ver como a RAIZ chegou nesses números</summary><div className="ux2-proof-body">
      {latest?.responsePayload.prescription.diagnosis.length?<div className="narrative-block"><h4>Diagnóstico usado</h4><ul>{latest.responsePayload.prescription.diagnosis.map((item,i)=><li key={i}><strong>{item.parameterCode}</strong> — {item.value} {item.unit} · {item.interpretation}<br/><small>{item.rationale}</small></li>)}</ul></div>:null}
      {latest?.responsePayload.prescription.managementPractices.length?<div className="narrative-block"><h4>Práticas de manejo consideradas</h4><ul>{latest.responsePayload.prescription.managementPractices.map((item,i)=><li key={i}>{item}</li>)}</ul></div>:null}
      {context&&<div className="ux2-context-card"><h4>Contexto determinístico de P e K</h4><p>Meta: <strong>{context.yieldGoal??"não informada"}{context.yieldGoalUnit?` ${context.yieldGoalUnit}`:""}</strong> · cultivo após a análise: <strong>{context.cultivationOrderAfterSoilAnalysis?`${context.cultivationOrderAfterSoilAnalysis}º`:"não informado"}</strong>{context.cropProfileCode?<> · cultura: <strong>{context.cropProfileCode}</strong></>:null}</p>{uniformPkReadiness&&<div className="review-grid">{(["P2O5","K2O"] as const).map((nutrient)=>{const state=uniformPkReadiness.nutrients[nutrient];const dose=context.deterministicPkDoses[nutrient];return <div className="review-summary" key={nutrient}><span>{nutrient}</span><strong>{state.ready&&uniformPkReadiness.ruleReady?`${state.soilLevel??"—"} · ${doseLabel(dose)}`:"Bloqueado"}</strong>{state.ready?<small>{state.basis==="SINGLE_SAMPLE"?"Base: amostra classificada.":`Predominância: ${state.matchingCount}/${state.totalCount} pontos.`}</small>:state.blockers.map((b)=><small key={b}>{blockerLabel(b)}</small>)}</div>;})}</div>}{canRun&&(!pkReadiness?.ready||!uniformPkReadiness?.ready)&&<div className="narrative-review-form"><p className="report-empty-note">A RAIZ pede somente as informações que realmente mudam o cálculo.</p><div className="review-grid"><label className="review-summary"><span>Meta de produtividade</span><input type="number" min="0.1" step="0.1" inputMode="decimal" value={contextYieldGoal} onChange={(e)=>setContextYieldGoal(e.target.value)} placeholder="Ex.: 4.2"/><small>t/ha</small></label><label className="review-summary"><span>Qual cultivo depois desta análise?</span><select value={contextCultivationOrder} onChange={(e)=>setContextCultivationOrder(e.target.value)}><option value="">Selecione</option><option value="1">1º cultivo</option><option value="2">2º cultivo</option></select></label></div><button className="button secondary" disabled={contextBusy} onClick={()=>void saveRecommendationContext()}>{contextBusy?"Salvando…":"Salvar e recalcular"}</button></div>}</div>}
      {latest?.responsePayload.prescription.sources.length?<div className="narrative-block muted"><h4>Fontes técnicas</h4><ul>{latest.responsePayload.prescription.sources.map((item,i)=><li key={i}>{item.title}{item.institution?` — ${item.institution}`:""}{item.url?<> · <a href={item.url} target="_blank" rel="noreferrer">abrir fonte</a></>:""}</li>)}</ul></div>:null}
      {latest?.reviewerNote&&<p className="narrative-reviewer-note"><strong>Observação registrada{latest.reviewedByName?` por ${latest.reviewedByName}`:""}:</strong> {latest.reviewerNote}</p>}
      {usage&&<p className="report-empty-note">Uso do recurso assistido: {usage.usedThisMonth}/{usage.monthlyLimit} gerações neste mês.</p>}
      {history.length>1&&<details className="agro-history"><summary>Histórico de versões ({history.length})</summary><ul>{history.map((item)=><li key={item.id}>{STATUS_META[item.status]?.label??item.status} · {new Date(item.createdAt).toLocaleString("pt-BR")}{item.reviewedByName?` · ${item.reviewedByName}`:""}</li>)}</ul></details>}
    </div></details>
  </section>;
}
